name: Go Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    env:
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
          cache: false

      - name: Build
        run: go build cmd/arc/main.go

      - name: Test
        run: go test -v ./...
